apiVersion: v1
kind: Service 
metadata:
  name: rexa-frontend-nodeport 
spec:
  type: NodePort
  selector: 
    app: rexa-frontend
  ports:  
    - port: 80
      targetPort: 5173
      protocol: TCP 
      nodePort: 30081